import os

TREASURY_DBNAME = os.environ['TREASURY_DBNAME']

PAYROLL_DBNAME = os.environ['PAYROLL_DBNAME']

SECURIT_DBNAME = os.environ['SECURIT_DBNAME']

INVENTORY_DBNAME = os.environ['INVENTORY_DBNAME']

ACCOUNT_DBNAME = os.environ['ACCOUNT_DBNAME']

ADMINIS_DBNAME = os.environ['ADMINIS_DBNAME']

INVOICING_DBNAME = os.environ['INVOICING_DBNAME']
